# Generated by Django 4.0 on 2022-03-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_image',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
