# Generated by Django 4.0 on 2022-03-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_food_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
