# Generated by Django 4.0 on 2022-03-27 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_alter_food_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food_image',
            old_name='Kid',
            new_name='kid',
        ),
    ]
